spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  messages:
    basename: messages

  # H2 Web Console (H2ConsoleProperties)
  h2:
    console:
      enabled: true
      path: /h2-console